### ISSUE TITLE
ui route access

### ISSUE THREAD

**Issue by webmclink** [romanzipp/Laravel-Queue-Monitor#120]
The UI route middleware is not working, I tried to add 'auth' middleware but it redirect me back to the previous page.  Is there any setting need to do? Thank you

**Comment by romanzipp** [comment]
I believe only adding the `auth` middleware won't work since the middleware responsible for parsing cookies and starting the session in the first place are missing. Could you try adding the `web` middleware group instead? (if you have configured it that way)

See https://github.com/laravel/laravel/blob/10.x/app/Http/Kernel.php#L32

**Comment by Chris1234567899** [comment]
In my case (using sanctum and jetstream, I put:
 'route' => [
            'prefix' => 'jobs',
            'middleware'=> ['web','auth:sanctum', config('jetstream.auth_session'), 'verified']
  ],
  
  That seems to do the trick

**Comment by webmclink** [comment]
The `'auth:sanctum'` did the trick. Thanks @Chris1234567899 and @romanzipp
