### ISSUE TITLE
Retry and delete buttons in GUI

### ISSUE THREAD

**Issue by BernhardK91** [romanzipp/Laravel-Queue-Monitor#49]
Adding the following functionalities would make a huge benefitfor queue monitor:

- "Retry"-Button in every failed line to push it back to queue after fixing the issue.
- "Delete"-Button in every line to delete a single entry from the monitor table.
- "Clear History" Button to delete all entries from monitor table.

Best Regards,
Bernhard

**Comment by romanzipp** [comment]
I've added the delete & purge buttons for version [2.0.25](https://github.com/romanzipp/Laravel-Queue-Monitor/releases/tag/2.0.25).

Although I don't think a "Retry" action is possible since jobs may receive certain parameters when dispatched. These serialized parameters are not available after a job has finished/failed.

![preview](https://user-images.githubusercontent.com/11266773/107770947-5403d480-6d3a-11eb-88b5-41d26d7f7f6f.png)

**Comment by BernhardK91** [comment]
Awesome!

Because failed jobs are saved in the failed_jobs table (including payload) it should work. If we do not have the ID on the job it can work with `php artisan queue:retry all` to retry all failed jobs.

See also at https://laravel.com/docs/8.x/queues#retrying-failed-jobs

In the link is also described how all failed jobs can be deleted (`queue:flush`).

**Comment by mattdavenport** [comment]
@romanzipp A retry button would be great (if `failed_jobs` table exists). Is this a contribution you would be willing to accept? Thanks!

**Comment by bosse-online** [comment]
@romanzipp Any news for the retry button?

**Comment by Michel-Verhoeven** [comment]
I recently created the retry button for a project we needed it for. I saw this issue was still open and the desire for this functionality is still active (based on @bosse-online  question) so made a quick PR yesterday. @romanzipp hope this helps implementing the retry option.

**Comment by bosse-online** [comment]
Thank you @Michel-Verhoeven !!
@romanzipp Can you merge it?
